### ISSUE TITLE
distutils package is deprecated and slated for removal in Python 3.12

### ISSUE THREAD

**Issue by pwkooij** [alguoo314/JASPER#11]
I received an error towards the end of the installation:

```
checking for the distutils Python package... no
configure: error: cannot import Python module "distutils".
Please check your Python installation. The error was:
<string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
```

It seems like it did deploy the software, `./jasper.sh -h` works, will do a test later to see if it will run full.

**Comment by pwkooij** [comment]
managed to install the v1.0.3 and get it running, but encountering yet another BioPython deprecation problem as mentioned in issue #7 

```
/lib/python3.10/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
warnings.warn(
Traceback (most recent call last):
File "/home/jasper-1.0.3/bin/jasper.py", line 10, in
import dna_jellyfish as jf
ImportError: bad magic number in 'dna_jellyfish': b'a\r\r\n'
```

The python script will have to be recoded to fit the new Bio.Align.PairwiseAligner. It doesn't seem like a quick recoding of the module will be sufficient from what I can see in the module descriptions.

I don't have enough time on my hands to try and solve this, so for now I will give up on using this.

**Comment by alguoo314** [comment]
Hi,

Thank you for spotting this. 

I took a look at the code and I think the BiopythonDeprecationWarning and the Jellyfish import error are two separate things. The pairwise2 package from Biopython imported in the jasper.py script is actually not needed in the script anymore, so I will remove that line in the next release soon. You can also fix it by removing the two lines of the import from Biopython in jasper.py. 

For the bad magic number error, could you confirm with me that you installed the 1.0.4 version from here: https://github.com/alekseyzimin/JASPER_release/releases? If yes, could you try using python3.8 for the binding to Jellyfish step in my README? That should probably solve the problem. I will look into the distutils alternatives in the near future so that it will support later Python versions.

Best,
Alina

**Comment by alguoo314** [comment]
Hi,

Thank you for spotting this. I think Bio.pairwise2 warning and the Jellyfish errors are two unrelated parts. I will re-code the line that uses Bio.pairwise2 soon. For the Jellyfish error, could you install the 1.0.4 version from here https://github.com/alekseyzimin/JASPER_release/releases and let me know if the error persists?

Best,
Alina

**Comment by pwkooij** [comment]
That was the version I had tried before (should have mentioned...), and I tried again, still getting the same error.

Here's the full install output in case that helps:
```
+ pwd -P
+ ROOT=/usr/local/bioinf/JASPER-1.0.4
+ [ -z  ]
+ DEST=/usr/local/bioinf/JASPER-1.0.4
+ mkdir -p dist-bin
+ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/bioinf/JASPER-1.0.4/dist-bin
+ which make
+ ln -sf /usr/bin/make /usr/local/bioinf/JASPER-1.0.4/dist-bin/gmake
+ grep -c ^processor /proc/cpuinfo
+ export NUM_THREADS=20
+ BINDIR=/usr/local/bioinf/JASPER-1.0.4/bin
+ LIBDIR=/usr/local/bioinf/JASPER-1.0.4/lib
+ export PKG_CONFIG_PATH=/usr/local/bioinf/JASPER-1.0.4/lib/pkgconfig:
+ cd global-1
+ ./configure --prefix=/usr/local/bioinf/JASPER-1.0.4 --bindir=/usr/local/bioinf/JASPER-1.0.4/bin --libdir=/usr/local/bioinf/JASPER-1.0.4/lib
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking how to print strings... printf
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... none
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) none
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... none
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for pthread_create in -lpthread... yes
checking for library containing clock_gettime... none required
checking for _NSGetExecutablePath... no
checking if std::thread::sleep_for is supported... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... yes
checking for getpagesize... yes
checking for working mmap... yes
checking for mremap... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for zlibVersion in -lz... yes
checking bzlib.h usability... yes
checking bzlib.h presence... yes
checking for bzlib.h... yes
checking for BZ2_bzlibVersion in -lbz2... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for __builtin_prefetch... yes
checking for architecture... Linux-amd64
checking for yaggo... /usr/local/bin/yaggo
checking for perl... /usr/bin/perl
checking for Perl prefix... /usr
checking for Perl extension include path... /usr/lib/x86_64-linux-gnu/perl/5.34/CORE
checking for Perl extension target directory... $(libdir)/perl
checking for Perl extensions C preprocessor flags... -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include
checking for Perl extensions linker flags... -shared -L/usr/local/lib -fstack-protector-strong
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating JASPER/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
+ make -j 20 install-special
Making install in JASPER pwd /usr/local/bioinf/JASPER-1.0.4/global-1
make[1]: Entering directory '/usr/local/bioinf/JASPER-1.0.4/global-1/JASPER'
make[2]: Entering directory '/usr/local/bioinf/JASPER-1.0.4/global-1/JASPER'
make[2]: Nothing to be done for 'install-data-am'.
 /usr/bin/mkdir -p '/usr/local/bioinf/JASPER-1.0.4/bin'
 /usr/bin/install -c src/jasper.sh src/jasper.py src/jellyfish.py jellyfish-2.3.0.tar.gz '/usr/local/bioinf/JASPER-1.0.4/bin'
make[2]: Leaving directory '/usr/local/bioinf/JASPER-1.0.4/global-1/JASPER'
make[1]: Leaving directory '/usr/local/bioinf/JASPER-1.0.4/global-1/JASPER'
+ cd global-1/JASPER
+ tar xzf jellyfish-2.3.0.tar.gz
+ cd jellyfish-2.3.0
+ ./configure --prefix /usr/local/bioinf/JASPER-1.0.4 --enable-python-binding
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking how to print strings... printf
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for ld... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking for shared library run path origin... done
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for g++... g++
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking 32-bit host C ABI... no
checking for ELF binary format... yes
checking for the common suffixes of directories in the library search path... lib,lib,lib64
checking for HTSLIB... yes
checking for samtools... /usr/bin/samtools
checking for unix2dos... no
checking for md5sum... md5sum
checking for yaggo... /usr/local/bin/yaggo
checking for x86 cpuid  output... unknown
checking for x86-AVX xgetbv  output... unknown
checking for x86 cpuid 0x00000000 output... 16:756e6547:6c65746e:49656e69
checking for x86 cpuid 0x80000000 output... 80000008:0:0:0
checking for x86 cpuid 0x00000001 output... a0655:5200800:7ffafbbf:bfebfbff
checking for x86 cpuid 0x00000007 output... 0:29c67af:40000018:bc000600
checking for x86 cpuid 0x80000001 output... 0:0:121:2c100800
checking for x86-AVX xgetbv 0x00000000 output... 21f:0
checking whether RDRND is supported by the processor... yes
checking whether RDRND is supported by the processor and OS... yes
checking whether C++ compiler accepts -mrdrnd... yes
checking whether BMI1 is supported by the processor... yes
checking whether BMI1 is supported by the processor and OS... yes
checking whether C++ compiler accepts -mbmi... yes
checking whether BMI2 is supported by the processor... yes
checking whether BMI2 is supported by the processor and OS... yes
checking whether C++ compiler accepts -mbmi2... yes
checking whether ADX is supported by the processor... yes
checking whether ADX is supported by the processor and OS... yes
checking whether C++ compiler accepts -madx... yes
checking whether MPX is supported by the processor... yes
checking whether MPX is supported by the processor and OS... yes
checking whether C++ compiler accepts -mmpx... yes
checking whether PREFETCHWT1 is supported by the processor... no
checking whether ABM is supported by the processor... yes
checking whether ABM is supported by the processor and OS... yes
checking whether C++ compiler accepts -mabm... yes
checking whether MMX is supported by the processor... yes
checking whether MMX is supported by the processor and OS... yes
checking whether C++ compiler accepts -mmmx... yes
checking whether SSE is supported by the processor... yes
checking whether SSE is supported by the processor and OS... yes
checking whether C++ compiler accepts -msse... yes
checking whether SSE2 is supported by the processor... yes
checking whether SSE2 is supported by the processor and OS... yes
checking whether C++ compiler accepts -msse2... yes
checking whether SSE3 is supported by the processor... yes
checking whether SSE3 is supported by the processor and OS... yes
checking whether C++ compiler accepts -msse3... yes
checking whether SSSE3 is supported by the processor... yes
checking whether SSSE3 is supported by the processor and OS... yes
checking whether C++ compiler accepts -mssse3... yes
checking whether SSE4.1 is supported by the processor... yes
checking whether SSE4.1 is supported by the processor and OS... yes
checking whether C++ compiler accepts -msse4.1... yes
checking whether SSE4.2 is supported by the processor... yes
checking whether SSE4.2 is supported by the processor and OS... yes
checking whether C++ compiler accepts -msse4.2... yes
checking whether SSE4a is supported by the processor... no
checking whether SHA is supported by the processor... no
checking whether AES is supported by the processor... yes
checking whether AES is supported by the processor and OS... yes
checking whether C++ compiler accepts -maes... yes
checking whether AVX is supported by the processor... yes
checking whether AVX is supported by the processor and OS... yes
checking whether C++ compiler accepts -mavx... yes
checking whether FMA3 is supported by the processor... yes
checking whether FMA3 is supported by the processor and OS... yes
checking whether C++ compiler accepts -mfma... yes
checking whether FMA4 is supported by the processor... no
checking whether XOP is supported by the processor... no
checking whether AVX2 is supported by the processor... yes
checking whether AVX2 is supported by the processor and OS... yes
checking whether C++ compiler accepts -mavx2... yes
checking whether AVX512-F is supported by the processor... no
checking whether AVX512-CD is supported by the processor... no
checking whether AVX512-PF is supported by the processor... no
checking whether AVX512-ER is supported by the processor... no
checking whether AVX512-VL is supported by the processor... no
checking whether AVX512-BW is supported by the processor... no
checking whether AVX512-DQ is supported by the processor... no
checking whether AVX512-IFMA is supported by the processor... no
checking whether AVX512-VBMI is supported by the processor... no
checking for __int128... yes
checking for std::numeric_limits<__int128>... yes
checking for _NSGetExecutablePath... no
checking for execinfo.h... yes
checking for ext/stdio_filebuf.h... yes
checking for sys/syscall.h... yes
checking for siginfo_t.si_int... yes
checking for python... /usr/bin/python
checking for a version of Python >= '2.1.0'... yes
checking for the distutils Python package... no
configure: error: cannot import Python module "distutils".
Please check your Python installation. The error was:
<string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
```

**Comment by vidsvur** [comment]
> Hi,
> 
> Thank you for spotting this. I think Bio.pairwise2 warning and the Jellyfish errors are two unrelated parts. I will re-code the line that uses Bio.pairwise2 soon. For the Jellyfish error, could you install the 1.0.4 version from here https://github.com/alekseyzimin/JASPER_release/releases and let me know if the error persists?
> 
> Best, Alina

This error still exists for the 1.0.4 version. This just depends on the python version used. Python version 3.8.1 works, but once the python version is 3.10, this error pops up

**Comment by alguoo314** [comment]
Thank you. I will take a look and get back to you.

**Comment by alguoo314** [comment]
We released the 1.0.5 version which addressed the distutils error and the Biopython warnings. Hope this helps! Let me know if you encounter any other issues! 
https://github.com/alekseyzimin/JASPER_release/releases

**Comment by pwkooij** [comment]
The distutils error during installation is gone, and it seemed to have installed properly. However, now I receive the following (common?) error:
```
Traceback (most recent call last):
  File "/usr/local/bioinf/JASPER-1.0.5/bin/jasper.py", line 9, in <module>
    import dna_jellyfish as jf
ImportError: bad magic number in 'dna_jellyfish': b'o\r\r\n'
```

**Comment by alguoo314** [comment]
Could you try going into the subfolder "YourPathTo/JASPER-1.0.5/global-1/JASPER/jellyfish-2.3.1" and run the following command:

./configure --prefix=$HOME/.local --enable-python-binding=$HOME/.local/lib/python3.8/site-packages --enable-swig

to explictly re-build the python binding with Jellyfish>

The path to python 3.8 can be replaced with your own python3.x path.

Hope that can help!

**Comment by pwkooij** [comment]
Getting the same error:

```
Traceback (most recent call last):
  File "/usr/local/bioinf/JASPER-1.0.5/bin/jasper.py", line 9, in <module>
    import dna_jellyfish as jf
ImportError: bad magic number in 'dna_jellyfish': b'o\r\r\n'
```

any other suggestions?

**Comment by alekseyzimin** [comment]
What is the version of python installed on your system?

**Comment by pwkooij** [comment]
So I have various versions, including installed natively and with bioconda. I guess the question is which one it is using. Any idea how I can figure that out?

As a side note, it would really help to have a conda build for this. Would be more easy for people to get it installed with all the  dependencies without any issues.

**Comment by pwkooij** [comment]
ok, I was able to resolve this problem by changing the shebang and directing the python scripts to the system version (python 3.10) -> from `#!/usr/bin/env python` to `#!/usr/bin/python`

However, now I encounter a new error:
```
Traceback (most recent call last):
  File "/usr/local/bioinf/JASPER-1.0.5/bin/jasper.py", line 8, in <module>
    from Bio.Align import PairwiseAligner
ModuleNotFoundError: No module named 'Bio'
```
I can she this refers to the biopython install, which seemed not to have been installed for that specific python installation. I now managed to get that installed for this version and running again.

**Comment by pwkooij** [comment]
ok! this worked! I was a bit fiddling around but it worked!
