### ISSUE TITLE
Invalid unit and unknown format k-mer

### ISSUE THREAD

**Issue by Meer9234** [alguoo314/JASPER#7]
Hi I am trying to polish a genome that has been assembled with flye. However, I get this error:

[Tue Sep  5 14:12:19 CEST 2023] Using BATCH SIZE 25000000
[Tue Sep  5 14:12:19 CEST 2023] Creating jellyfish database mer_counts50.jf
Invalid uint64_t '5.72607e+09' for [-s, --size=uint64]: Invalid character
Unknown format ''
[Tue Sep  5 14:12:19 CEST 2023] Computing K-mer histogram
Unknown format ''
[Tue Sep  5 14:12:19 CEST 2023] Computing mer counts histogram from mer_counts50.jf failed, please make sure that mer_counts50.jf is a valid Jellyfish mer counts file

This is what I ran:
./jasper.sh -a assembly.fasta -r Loading34.fastq -t 8 -k 50 -p 3 1>jasper.out 2>&1

Thanks in advance!

**Comment by alguoo314** [comment]
Hi, 

Could you try if this tar ball works?

Best wishes
Alina
[jasper-1.0.2-modified.tar.gz](https://github.com/alguoo314/JASPER/files/12542502/jasper-1.0.2-modified.tar.gz)

**Comment by Meer9234** [comment]
Hi thanks for the reply.
This is what I get now. It is slightly different.

[Fri Sep  8 13:42:53 CEST 2023] Using BATCH SIZE 25000000
[Fri Sep  8 13:42:53 CEST 2023] Splitting query into batches for parallel execution
[Fri Sep  8 13:43:03 CEST 2023] Creating jellyfish database mer_counts50.jf
Invalid uint64_t '-m' for [-s, --size=uint64]: Negative value
Unknown format ''
[Fri Sep  8 13:43:03 CEST 2023] Computing K-mer histogram
Unknown format ''
[Fri Sep  8 13:43:03 CEST 2023] Computing mer counts histogram from mer_counts50.jf failed, please make sure that mer_counts50.jf is a valid Jellyfish mer counts file

Thanks!

**Comment by alguoo314** [comment]
Sorry for still leaving a small error. Could you give a try of this new release?
[jasper-1.0.3 (2).tar.gz](https://github.com/alguoo314/JASPER/files/12568554/jasper-1.0.3.2.tar.gz)

**Comment by Meer9234** [comment]
Hi tThanks! And no problem that is part of it :) 
However the format of the file is not recognised? I cannot tar it.

**Comment by alguoo314** [comment]
Hmm sorry this is unexpected. I previously just copied the tarball that I uploaded into the repo, and I thought it would work fine. I tried downloading the tarball from the repo main page just now and it unzipped correctly. I've edited the file attachment from the last comment. If it still does not work, you can download the tarball from the repo main page. I'll officially publish the new release soon as well.

**Comment by Meer9234** [comment]
Thanks! The previous errors are gone now! 

But now I still get something weird did I not set up Jellyfish correctly? I get this:

[Tue Sep 12 12:30:38 CEST 2023] Using BATCH SIZE 25000000
[Tue Sep 12 12:30:38 CEST 2023] Creating jellyfish database mer_counts50.jf
/home/jasper-1.0.3/bin/jasper.sh: line 177:  : command not found
[Tue Sep 12 13:09:24 CEST 2023] Polishing
[Tue Sep 12 13:09:24 CEST 2023] Lower threshold for unreliable kmers is 2
[Tue Sep 12 13:09:26 CEST 2023] Polishing failed

But line 177 in jasper.sh is:
mv jfhisto$KMER.csv.tmp jfhisto$KMER.csv && \ 

The mv command should work. So idk what goes wrong

**Comment by alguoo314** [comment]
Hi,

The /home/jasper-1.0.3/bin/jasper.sh: line 177: : command not found error is due to an extra space at the end of the line which I will fix. But as I tested on my side, it would not interrupt the running process. So I think your polishing failed due to another reason. Could you check the jasper.err file and see what it says?

Best,
Alina

**Comment by Meer9234** [comment]
Ah I see. It is the bad magic number error. But I saw another issue where it got resolved so I'll try that.

/lib/python3.10/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(
Traceback (most recent call last):
  File "/home/jasper-1.0.3/bin/jasper.py", line 10, in <module>
    import dna_jellyfish as jf
ImportError: bad magic number in 'dna_jellyfish': b'a\r\r\n'

**Comment by vidsvur** [comment]
> Hi thanks for the reply. This is what I get now. It is slightly different.
> 
> [Fri Sep 8 13:42:53 CEST 2023] Using BATCH SIZE 25000000 [Fri Sep 8 13:42:53 CEST 2023] Splitting query into batches for parallel execution [Fri Sep 8 13:43:03 CEST 2023] Creating jellyfish database mer_counts50.jf Invalid uint64_t '-m' for [-s, --size=uint64]: Negative value Unknown format '' [Fri Sep 8 13:43:03 CEST 2023] Computing K-mer histogram Unknown format '' [Fri Sep 8 13:43:03 CEST 2023] Computing mer counts histogram from mer_counts50.jf failed, please make sure that mer_counts50.jf is a valid Jellyfish mer counts file
> 
> Thanks!

Hi all,

I'm currently using jasper-1.0.4, and I'm running into this error as well. Should I use the release linked on this issue thread (1.0.3)?

**Comment by pwkooij** [comment]
> /lib/python3.10/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
> warnings.warn(
> Traceback (most recent call last):
> File "/home/jasper-1.0.3/bin/jasper.py", line 10, in
> import dna_jellyfish as jf
> ImportError: bad magic number in 'dna_jellyfish': b'a\r\r\n'

any solution for this? This has to do with deprecation of a module within BioPython, but it would need coding throughout to make it all fit with the newer Bio.Align.PairwiseAligner as far as I can see

**Comment by alguoo314** [comment]
Hi vidsvur,

This is peculiar. I checked the 1.0.4 release and the line about $JF_SIZE (which is the argument for -s) is exactly the same between the 1.0.4 release and the attached tarball's release, so there should not be a difference. Could you check if the input files are all nonempty and provide me with your input commands when you ran jasper so that I can look into it?


> > Hi thanks for the reply. This is what I get now. It is slightly different.
> > [Fri Sep 8 13:42:53 CEST 2023] Using BATCH SIZE 25000000 [Fri Sep 8 13:42:53 CEST 2023] Splitting query into batches for parallel execution [Fri Sep 8 13:43:03 CEST 2023] Creating jellyfish database mer_counts50.jf Invalid uint64_t '-m' for [-s, --size=uint64]: Negative value Unknown format '' [Fri Sep 8 13:43:03 CEST 2023] Computing K-mer histogram Unknown format '' [Fri Sep 8 13:43:03 CEST 2023] Computing mer counts histogram from mer_counts50.jf failed, please make sure that mer_counts50.jf is a valid Jellyfish mer counts file
> > Thanks!
> 
> Hi all,
> 
> I'm currently using jasper-1.0.4, and I'm running into this error as well. Should I use the release linked on this issue thread (1.0.3)?

**Comment by vidsvur** [comment]
@alguoo314 thanks for your reply.

I recreated the error with 1.0.4:
```
[Mon Jun 24 03:19:09 PM EDT 2024] Using BATCH SIZE 25000000
[Mon Jun 24 03:19:10 PM EDT 2024] Creating jellyfish database mer_counts37.jf
Unknown format ''
[Mon Jun 24 03:25:46 PM EDT 2024] Computing K-mer histogram
Unknown format ''
[Mon Jun 24 03:25:46 PM EDT 2024] Computing mer counts histogram from mer_counts37.jf failed, please make sure that mer_counts37.jf is a valid Jellyfish mer counts file
```

Here is my input script:
```
NUMTH=32
DRAFT=assembly_3kb.fa
R1=illumina.550_unclassified_1.fastq
R2=illumina.550_unclassified_2.fastq

module load python/3.8.1
source jasper-1.0.4/bin/activate
export PATH=/core/globus/cgi/Physcomitrellopsis_africana/tsuga_flye/jasper/jasper-1.0.4/jellyfish-2.3.1/bin/:$PATH

jasper-1.0.4/JASPER-1.0.4/bin/jasper.sh --reads 'illumina.550_unclassified_1.fastq illumina.550_unclassified_2.fastq' -a $DRAFT -t $NUMTH -d -v -p 2 1> jasper_trial_run.out 2>&1
```

My inputs files are all non-empty
```
17224499063 Apr 19 16:41 assembly_3kb.fa
1409516706129 Dec 16  2023 illumina.550_unclassified_1.fastq
1409427006719 Dec 16  2023 illumina.550_unclassified_2.fastq
```



> Hi vidsvur,
> 
> This is peculiar. I checked the 1.0.4 release and the line about $JF_SIZE (which is the argument for -s) is exactly the same between the 1.0.4 release and the attached tarball's release, so there should not be a difference. Could you check if the input files are all nonempty and provide me with your input commands when you ran jasper so that I can look into it?
> 
> > > Hi thanks for the reply. This is what I get now. It is slightly different.
> > > [Fri Sep 8 13:42:53 CEST 2023] Using BATCH SIZE 25000000 [Fri Sep 8 13:42:53 CEST 2023] Splitting query into batches for parallel execution [Fri Sep 8 13:43:03 CEST 2023] Creating jellyfish database mer_counts50.jf Invalid uint64_t '-m' for [-s, --size=uint64]: Negative value Unknown format '' [Fri Sep 8 13:43:03 CEST 2023] Computing K-mer histogram Unknown format '' [Fri Sep 8 13:43:03 CEST 2023] Computing mer counts histogram from mer_counts50.jf failed, please make sure that mer_counts50.jf is a valid Jellyfish mer counts file
> > > Thanks!
> > 
> > 
> > Hi all,
> > I'm currently using jasper-1.0.4, and I'm running into this error as well. Should I use the release linked on this issue thread (1.0.3)?

**Comment by alguoo314** [comment]
Could you add echo "$JF_SIZE" after line 82 in jasper.sh and let me know what it prints? Thank you!

**Comment by vidsvur** [comment]
@alguoo314 this was the output:
```
8
[Tue Jun 25 03:18:10 PM EDT 2024] Using BATCH SIZE 25000000
[Tue Jun 25 03:18:11 PM EDT 2024] Creating jellyfish database mer_counts37.jf
Unknown format ''
[Tue Jun 25 03:24:19 PM EDT 2024] Computing K-mer histogram
Unknown format ''
[Tue Jun 25 03:24:19 PM EDT 2024] Computing mer counts histogram from mer_counts37.jf failed, please make sure that mer_counts37.jf is a valid Jellyfish mer counts file
```

**Comment by alguoo314** [comment]
Hi vidsvur, 

My hypothesis for your error is that your read files may be symbolic links that are 40 bytes each, which made the calculated the JF_Size = sum(size of the two files)/10 = 4. Could you check if your reads path are not symbolic links.

Also, we released the 1.0.5 version which addressed the distutils error and the Biopython warnings. The version also caps JF_SIZE as an integer between 1e6 and 1e12. Hope this can solve the error!

https://github.com/alekseyzimin/JASPER_release/releases
